# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '_00login.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QProgressBar,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(640, 481)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 601, 461))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_devClose = QPushButton(self.tab)
        self.pushButton_devClose.setObjectName(u"pushButton_devClose")
        self.pushButton_devClose.setGeometry(QRect(120, 160, 75, 24))
        self.comboBox_bandRate_devCOM = QComboBox(self.tab)
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.setObjectName(u"comboBox_bandRate_devCOM")
        self.comboBox_bandRate_devCOM.setGeometry(QRect(110, 80, 69, 22))
        self.comboBox_bandRate_devCOM.setEditable(False)
        self.label_bandRate = QLabel(self.tab)
        self.label_bandRate.setObjectName(u"label_bandRate")
        self.label_bandRate.setGeometry(QRect(40, 120, 53, 16))
        self.label_bandRate_2 = QLabel(self.tab)
        self.label_bandRate_2.setObjectName(u"label_bandRate_2")
        self.label_bandRate_2.setGeometry(QRect(40, 80, 53, 16))
        self.pushButton_devOpen = QPushButton(self.tab)
        self.pushButton_devOpen.setObjectName(u"pushButton_devOpen")
        self.pushButton_devOpen.setGeometry(QRect(20, 160, 75, 24))
        self.comboBox_bandRate = QComboBox(self.tab)
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.setObjectName(u"comboBox_bandRate")
        self.comboBox_bandRate.setGeometry(QRect(110, 120, 69, 22))
        self.comboBox_bandRate.setEditable(False)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton = QPushButton(self.tab_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(360, 390, 75, 24))
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 350, 111, 21))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 300, 91, 21))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 131, 21))
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 160, 91, 21))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 260, 101, 16))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(80, 220, 53, 16))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(80, 240, 53, 16))
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 130, 53, 16))
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 280, 81, 21))
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 330, 91, 16))
        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 17, 16))
        self.lb_sn = QLabel(self.tab_2)
        self.lb_sn.setObjectName(u"lb_sn")
        self.lb_sn.setGeometry(QRect(210, 10, 141, 21))
        self.lb_uuid = QLabel(self.tab_2)
        self.lb_uuid.setObjectName(u"lb_uuid")
        self.lb_uuid.setGeometry(QRect(240, 130, 191, 16))
        self.lb_okey = QLabel(self.tab_2)
        self.lb_okey.setObjectName(u"lb_okey")
        self.lb_okey.setGeometry(QRect(240, 160, 181, 21))
        self.lb_usrkey = QLabel(self.tab_2)
        self.lb_usrkey.setObjectName(u"lb_usrkey")
        self.lb_usrkey.setGeometry(QRect(230, 220, 211, 21))
        self.lb_usrdata = QLabel(self.tab_2)
        self.lb_usrdata.setObjectName(u"lb_usrdata")
        self.lb_usrdata.setGeometry(QRect(230, 240, 201, 21))
        self.lb_mkeya = QLabel(self.tab_2)
        self.lb_mkeya.setObjectName(u"lb_mkeya")
        self.lb_mkeya.setGeometry(QRect(230, 260, 191, 21))
        self.lb_mkeyb = QLabel(self.tab_2)
        self.lb_mkeyb.setObjectName(u"lb_mkeyb")
        self.lb_mkeyb.setGeometry(QRect(230, 280, 191, 21))
        self.lb_musrdata = QLabel(self.tab_2)
        self.lb_musrdata.setObjectName(u"lb_musrdata")
        self.lb_musrdata.setGeometry(QRect(230, 310, 231, 21))
        self.lb_muuid = QLabel(self.tab_2)
        self.lb_muuid.setObjectName(u"lb_muuid")
        self.lb_muuid.setGeometry(QRect(230, 330, 211, 16))
        self.lb_vmuuid = QLabel(self.tab_2)
        self.lb_vmuuid.setObjectName(u"lb_vmuuid")
        self.lb_vmuuid.setGeometry(QRect(230, 350, 211, 21))
        self.pushButton_4 = QPushButton(self.tab_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(460, 390, 75, 24))
        self.lb_state = QLabel(self.tab_2)
        self.lb_state.setObjectName(u"lb_state")
        self.lb_state.setGeometry(QRect(10, 60, 541, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pb_selectbin = QPushButton(self.tab_3)
        self.pb_selectbin.setObjectName(u"pb_selectbin")
        self.pb_selectbin.setGeometry(QRect(60, 50, 75, 24))
        self.pb_state = QPushButton(self.tab_3)
        self.pb_state.setObjectName(u"pb_state")
        self.pb_state.setGeometry(QRect(50, 190, 75, 24))
        self.progressBar = QProgressBar(self.tab_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(180, 190, 118, 23))
        self.progressBar.setValue(0)
        self.lb_updatestate = QLabel(self.tab_3)
        self.lb_updatestate.setObjectName(u"lb_updatestate")
        self.lb_updatestate.setGeometry(QRect(160, 250, 181, 41))
        self.lb_binpath = QLabel(self.tab_3)
        self.lb_binpath.setObjectName(u"lb_binpath")
        self.lb_binpath.setGeometry(QRect(150, 80, 351, 41))
        self.lb_binsize = QLabel(self.tab_3)
        self.lb_binsize.setObjectName(u"lb_binsize")
        self.lb_binsize.setGeometry(QRect(150, 140, 311, 16))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pushButton_3 = QPushButton(self.tab_4)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 10, 75, 24))
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.pushButton_devClose.clicked.connect(Form.devClose)
        self.pb_selectbin.clicked.connect(Form.openBinFile)
        self.pushButton_4.clicked.connect(Form.test_end)
        self.comboBox_bandRate.currentTextChanged.connect(Form.modify_dwBtr)
        self.comboBox_bandRate_devCOM.currentTextChanged.connect(Form.select_dev_comm)
        self.pushButton_devOpen.clicked.connect(Form.devOpen)
        self.pb_state.clicked.connect(Form.startUpgrade)
        self.pushButton.clicked.connect(Form.test_start)

        self.tabWidget.setCurrentIndex(0)
        self.comboBox_bandRate_devCOM.setCurrentIndex(0)
        self.comboBox_bandRate.setCurrentIndex(7)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton_devClose.setText(QCoreApplication.translate("Form", u"\u5173\u95ed", None))
        self.comboBox_bandRate_devCOM.setItemText(0, QCoreApplication.translate("Form", u"USB1", None))
        self.comboBox_bandRate_devCOM.setItemText(1, QCoreApplication.translate("Form", u"USB2", None))
        self.comboBox_bandRate_devCOM.setItemText(2, QCoreApplication.translate("Form", u"USB3", None))
        self.comboBox_bandRate_devCOM.setItemText(3, QCoreApplication.translate("Form", u"USB4", None))
        self.comboBox_bandRate_devCOM.setItemText(4, QCoreApplication.translate("Form", u"USB5", None))
        self.comboBox_bandRate_devCOM.setItemText(5, QCoreApplication.translate("Form", u"USB6", None))
        self.comboBox_bandRate_devCOM.setItemText(6, QCoreApplication.translate("Form", u"USB7", None))
        self.comboBox_bandRate_devCOM.setItemText(7, QCoreApplication.translate("Form", u"USB8", None))
        self.comboBox_bandRate_devCOM.setItemText(8, QCoreApplication.translate("Form", u"USB9", None))
        self.comboBox_bandRate_devCOM.setItemText(9, QCoreApplication.translate("Form", u"USB10", None))
        self.comboBox_bandRate_devCOM.setItemText(10, QCoreApplication.translate("Form", u"USB11", None))
        self.comboBox_bandRate_devCOM.setItemText(11, QCoreApplication.translate("Form", u"USB12", None))
        self.comboBox_bandRate_devCOM.setItemText(12, QCoreApplication.translate("Form", u"USB13", None))
        self.comboBox_bandRate_devCOM.setItemText(13, QCoreApplication.translate("Form", u"USB14", None))
        self.comboBox_bandRate_devCOM.setItemText(14, QCoreApplication.translate("Form", u"USB15", None))
        self.comboBox_bandRate_devCOM.setItemText(15, QCoreApplication.translate("Form", u"USB16", None))

        self.comboBox_bandRate_devCOM.setCurrentText(QCoreApplication.translate("Form", u"USB1", None))
        self.label_bandRate.setText(QCoreApplication.translate("Form", u"\u6ce2\u7279\u7387", None))
        self.label_bandRate_2.setText(QCoreApplication.translate("Form", u"\u7aef\u53e3", None))
        self.pushButton_devOpen.setText(QCoreApplication.translate("Form", u"\u6253\u5f00", None))
        self.comboBox_bandRate.setItemText(0, QCoreApplication.translate("Form", u"5Kbps", None))
        self.comboBox_bandRate.setItemText(1, QCoreApplication.translate("Form", u"10Kbps", None))
        self.comboBox_bandRate.setItemText(2, QCoreApplication.translate("Form", u"20Kbps", None))
        self.comboBox_bandRate.setItemText(3, QCoreApplication.translate("Form", u"50Kbps", None))
        self.comboBox_bandRate.setItemText(4, QCoreApplication.translate("Form", u"100Kbps", None))
        self.comboBox_bandRate.setItemText(5, QCoreApplication.translate("Form", u"125Kbps", None))
        self.comboBox_bandRate.setItemText(6, QCoreApplication.translate("Form", u"250Kbps", None))
        self.comboBox_bandRate.setItemText(7, QCoreApplication.translate("Form", u"500Kbps", None))
        self.comboBox_bandRate.setItemText(8, QCoreApplication.translate("Form", u"800Kbps", None))
        self.comboBox_bandRate.setItemText(9, QCoreApplication.translate("Form", u"1000Kbps", None))

        self.comboBox_bandRate.setCurrentText(QCoreApplication.translate("Form", u"500Kbps", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u5f00\u542f\u8bbe\u5907", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u6a21\u62df\u5361\uff35\uff35\uff29\uff24", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\uff2d\u5361\u7528\u6237\u6570\u636e", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u5361\u7247\u4fe1\u606f\u5916\u8bbe\u72b6\u6001", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5916\u90e8\u8ba4\u8bc1\u5bc6\u94a5", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"M\u5361\u5bc6\u94a5A", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u7528\u6237\u5bc6\u94a5", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u7528\u6237\u6570\u636e", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"UUID", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"M\u5361\u5bc6\u94a5B", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\uff2d\u5361\uff35\uff35\uff29\uff24", None))
        self.label.setText(QCoreApplication.translate("Form", u"SN", None))
        self.lb_sn.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_uuid.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_okey.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_usrkey.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_usrdata.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_mkeya.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_mkeyb.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_musrdata.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_muuid.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.lb_vmuuid.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"\u7ed3\u675f", None))
        self.lb_state.setText(QCoreApplication.translate("Form", u"\u7a7a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u6d4b\u8bd5", None))
        self.pb_selectbin.setText(QCoreApplication.translate("Form", u"\u9009\u62e9\u6587\u4ef6", None))
        self.pb_state.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb", None))
        self.lb_updatestate.setText("")
        self.lb_binpath.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u8def\u5f84", None))
        self.lb_binsize.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u5927\u5c0f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Form", u"\u5347\u7ea7", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Form", u"\u5199\u53f7", None))
    # retranslateUi

