# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '_00login.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QPushButton,
    QSizePolicy, QTabWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(640, 481)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 10, 561, 461))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_devClose = QPushButton(self.tab)
        self.pushButton_devClose.setObjectName(u"pushButton_devClose")
        self.pushButton_devClose.setGeometry(QRect(120, 160, 75, 24))
        self.comboBox_bandRate_devCOM = QComboBox(self.tab)
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.addItem("")
        self.comboBox_bandRate_devCOM.setObjectName(u"comboBox_bandRate_devCOM")
        self.comboBox_bandRate_devCOM.setGeometry(QRect(110, 80, 69, 22))
        self.comboBox_bandRate_devCOM.setEditable(False)
        self.label_bandRate = QLabel(self.tab)
        self.label_bandRate.setObjectName(u"label_bandRate")
        self.label_bandRate.setGeometry(QRect(40, 120, 53, 16))
        self.label_bandRate_2 = QLabel(self.tab)
        self.label_bandRate_2.setObjectName(u"label_bandRate_2")
        self.label_bandRate_2.setGeometry(QRect(40, 80, 53, 16))
        self.pushButton_devOpen = QPushButton(self.tab)
        self.pushButton_devOpen.setObjectName(u"pushButton_devOpen")
        self.pushButton_devOpen.setGeometry(QRect(20, 160, 75, 24))
        self.comboBox_bandRate = QComboBox(self.tab)
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.addItem("")
        self.comboBox_bandRate.setObjectName(u"comboBox_bandRate")
        self.comboBox_bandRate.setGeometry(QRect(110, 120, 69, 22))
        self.comboBox_bandRate.setEditable(False)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton = QPushButton(self.tab_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 10, 75, 24))
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 320, 111, 21))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 270, 91, 21))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(81, 113, 131, 21))
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(81, 157, 91, 21))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(81, 223, 101, 16))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(81, 179, 53, 16))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(81, 201, 53, 16))
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(81, 135, 53, 16))
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(81, 245, 81, 21))
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 300, 91, 16))
        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 90, 17, 16))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(240, 90, 53, 16))
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(240, 110, 53, 16))
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(240, 130, 53, 16))
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(240, 160, 53, 16))
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(240, 180, 53, 16))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(240, 200, 53, 16))
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(230, 220, 53, 16))
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(230, 250, 53, 16))
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(230, 270, 53, 16))
        self.label_21 = QLabel(self.tab_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(230, 300, 53, 16))
        self.label_22 = QLabel(self.tab_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(230, 320, 53, 16))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pushButton_2 = QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 10, 75, 24))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pushButton_3 = QPushButton(self.tab_4)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 10, 75, 24))
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.pushButton_devOpen.clicked.connect(Form.devOpen)
        self.comboBox_bandRate.currentTextChanged.connect(Form.modify_dwBtr)
        self.comboBox_bandRate_devCOM.currentTextChanged.connect(Form.select_dev_comm)
        self.pushButton_devClose.clicked.connect(Form.devClose)
        self.pushButton.clicked.connect(Form.test_start)

        self.tabWidget.setCurrentIndex(1)
        self.comboBox_bandRate_devCOM.setCurrentIndex(0)
        self.comboBox_bandRate.setCurrentIndex(7)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton_devClose.setText(QCoreApplication.translate("Form", u"\u5173\u95ed", None))
        self.comboBox_bandRate_devCOM.setItemText(0, QCoreApplication.translate("Form", u"USB1", None))
        self.comboBox_bandRate_devCOM.setItemText(1, QCoreApplication.translate("Form", u"USB2", None))
        self.comboBox_bandRate_devCOM.setItemText(2, QCoreApplication.translate("Form", u"USB3", None))
        self.comboBox_bandRate_devCOM.setItemText(3, QCoreApplication.translate("Form", u"USB4", None))
        self.comboBox_bandRate_devCOM.setItemText(4, QCoreApplication.translate("Form", u"USB5", None))
        self.comboBox_bandRate_devCOM.setItemText(5, QCoreApplication.translate("Form", u"USB6", None))
        self.comboBox_bandRate_devCOM.setItemText(6, QCoreApplication.translate("Form", u"USB7", None))
        self.comboBox_bandRate_devCOM.setItemText(7, QCoreApplication.translate("Form", u"USB8", None))
        self.comboBox_bandRate_devCOM.setItemText(8, QCoreApplication.translate("Form", u"USB9", None))
        self.comboBox_bandRate_devCOM.setItemText(9, QCoreApplication.translate("Form", u"USB10", None))
        self.comboBox_bandRate_devCOM.setItemText(10, QCoreApplication.translate("Form", u"USB11", None))
        self.comboBox_bandRate_devCOM.setItemText(11, QCoreApplication.translate("Form", u"USB12", None))
        self.comboBox_bandRate_devCOM.setItemText(12, QCoreApplication.translate("Form", u"USB13", None))
        self.comboBox_bandRate_devCOM.setItemText(13, QCoreApplication.translate("Form", u"USB14", None))
        self.comboBox_bandRate_devCOM.setItemText(14, QCoreApplication.translate("Form", u"USB15", None))
        self.comboBox_bandRate_devCOM.setItemText(15, QCoreApplication.translate("Form", u"USB16", None))

        self.comboBox_bandRate_devCOM.setCurrentText(QCoreApplication.translate("Form", u"USB1", None))
        self.label_bandRate.setText(QCoreApplication.translate("Form", u"\u6ce2\u7279\u7387", None))
        self.label_bandRate_2.setText(QCoreApplication.translate("Form", u"\u7aef\u53e3", None))
        self.pushButton_devOpen.setText(QCoreApplication.translate("Form", u"\u6253\u5f00", None))
        self.comboBox_bandRate.setItemText(0, QCoreApplication.translate("Form", u"5Kbps", None))
        self.comboBox_bandRate.setItemText(1, QCoreApplication.translate("Form", u"10Kbps", None))
        self.comboBox_bandRate.setItemText(2, QCoreApplication.translate("Form", u"20Kbps", None))
        self.comboBox_bandRate.setItemText(3, QCoreApplication.translate("Form", u"50Kbps", None))
        self.comboBox_bandRate.setItemText(4, QCoreApplication.translate("Form", u"100Kbps", None))
        self.comboBox_bandRate.setItemText(5, QCoreApplication.translate("Form", u"125Kbps", None))
        self.comboBox_bandRate.setItemText(6, QCoreApplication.translate("Form", u"250Kbps", None))
        self.comboBox_bandRate.setItemText(7, QCoreApplication.translate("Form", u"500Kbps", None))
        self.comboBox_bandRate.setItemText(8, QCoreApplication.translate("Form", u"800Kbps", None))
        self.comboBox_bandRate.setItemText(9, QCoreApplication.translate("Form", u"1000Kbps", None))

        self.comboBox_bandRate.setCurrentText(QCoreApplication.translate("Form", u"500Kbps", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u5f00\u542f\u8bbe\u5907", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u6a21\u62df\u5361\uff35\uff35\uff29\uff24", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\uff2d\u5361\u7528\u6237\u6570\u636e", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u5361\u7247\u4fe1\u606f\u5916\u8bbe\u72b6\u6001", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5916\u90e8\u8ba4\u8bc1\u5bc6\u94a5", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"M\u5361\u5bc6\u94a5A", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u7528\u6237\u5bc6\u94a5", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u7528\u6237\u6570\u636e", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"UUID", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"M\u5361\u5bc6\u94a5B", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\uff2d\u5361\uff35\uff35\uff29\uff24", None))
        self.label.setText(QCoreApplication.translate("Form", u"SN", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u6d4b\u8bd5", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Form", u"\u5347\u7ea7", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Form", u"\u5199\u53f7", None))
    # retranslateUi

